modLoader = "kotlinforforge"
loaderVersion = "[4,)"

license = "GNU-GPL-3.0"
issueTrackerURL = "https://github.com/lilmods/aim-assistance/issues"

[[mods]]
modId = "motorassistance"
version = "2.1.0"
displayName = "MotorAssistance"
authors = "lilgallon"
description = '''
The only Minecraft Mod that helps to aim without giving an unfair PvP
advantage. Useful for new players that are not used to play on a computer.
Everything is configurable. Ideal to introduce Minecraft to your parents!
'''
updateJSONURL="https://raw.githubusercontent.com/lilmods/aim-assistance/main/updates.json"
logoFile="assets/motorassistance/icon.png"
[[dependencies.motorassistance]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.motorassistance]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
